# Generated by Django 3.2.20 on 2023-08-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230819_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='content',
        ),
        migrations.AddField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='Personal Introduction'),
        ),
    ]
