# Generated by Django 3.2.20 on 2024-01-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20230819_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='../default_profile_o5f3a0', upload_to='images/'),
        ),
    ]
