# Generated by Django 3.2.20 on 2024-01-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
    ]
